### ISSUE TITLE
REST external address setting doesn't work

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/ansible-neofs#21]
## Expected Behavior
https://rest.t5.fs.neo.org/v1/docs/ to show https://rest.t5.fs.neo.org/v1/ base URL (because of `neofs_rest__external_address: 'https://rest.t5.fs.neo.org'`)

## Current Behavior
`[ Base URL: localhost:8090/v1 ]`

## Possible Solution
Fix it.

**Comment by 532910** [comment]
fixed

**Comment by roman-khimov** [comment]
Fixed where?

**Comment by 532910** [comment]
Have you updated restgw to 0.7.1?

**Comment by 532910** [comment]
0. always do make
1. always do dry-run
2. go to jenkins and start it from there
